[package]
name = "llvm-sys"
version = "0.1.0"
authors = ["Peter Delevoryas <me@peterdelevoryas.com>"]
edition = "2018"
build = "build.rs"

[profile.dev]
debug = false
lto = false

[dependencies]

[build-dependencies]
bindgen = "0.40.0"
